@server=http://localhost:4004
@username=alice
@password=
@clientid=sb-Franco-Proxy!t430848
@ClientIdSecret=021d62a9-01c6-4f21-acac-3c7bf401d5ad$kbyIfCwd7KRYMsxS1Wh4M8ErfIgeRK0giyT2CEyzTC4=

### Get JWT token from XSUAA
POST {{server}}/proxy/A_PurchaseContract/oauth/token
Authorization: Basic <base64({{clientid}}:{{ClientIdSecret}})>
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

'sb-Franco-Proxy!t430848:021d62a9-01c6-4f21-acac-3c7bf401d5ad$kbyIfCwd7KRYMsxS1Wh4M8ErfIgeRK0giyT2CEyzTC4='
curl -u '' \
  -d 'grant_type=client_credentials' \
  'http://localhost:4004/proxy/A_PurchaseContract/oauth/token'

curl -X POST \
  http://localhost:4004/proxy/A_PurchaseContract/oauth/token \
  -H "Authorization: Basic c2ItRnJhbmNvLVByb3h5IXQ0MzA4NDg6MDIxZDYyYTktMDFjNi00ZjIxLWFjYWMtM2M3YmY0MDFkNWFkJGtieUlmQ3dkN0tSWU1zeFMxV2g0TThFcmZJZ2VSSzBnaXlUMkNFeXpUQzQ9" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "grant_type=client_credentials"

### A_PurchaseContract
# @name A_PurchaseContract_GET
GET {{server}}/proxy/A_PurchaseContract
Authorization: Basic {{username}}:{{password}}


### A_PurchaseContractItem
# @name A_PurchaseContractItem_GET
GET {{server}}/proxy/A_PurchaseContractItem
Authorization: Basic {{username}}:{{password}}


### A_PurchaseContractItem
# @name A_PurchaseContractItem_POST
POST {{server}}/proxy/A_PurchaseContractItem
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "PurchaseContract": "em-8676876",
  "PurchaseContractItem": "76876",
  "PurchasingContractDeletionCode": "6",
  "PurchaseContractItemText": "PurchaseContractItemText-8676876",
  "CompanyCode": "6876",
  "Plant": "6876",
  "StorageLocation": "6876",
  "RequirementTracking": "ng-8676876",
  "MaterialGroup": "p-8676876",
  "SupplierMaterialNumber": "SupplierMaterialNumber-8676876",
  "OrderQuantityUnit": "876",
  "OrderQuantityUnitISOCode": "876",
  "TargetQuantity": 24169220.239,
  "PurgDocReleaseOrderQuantity": 15239752.266,
  "OrderPriceUnit": "876",
  "OrderPriceUnitISOCode": "876",
  "OrderPriceUnitToOrderUnitNmrtr": 92250,
  "OrdPriceUnitToOrderUnitDnmntr": 32446,
  "ContractNetPriceAmount": 16349830.795,
  "DocumentCurrency": "76876",
  "NetPriceQuantity": 53292,
  "TaxCode": "76",
  "TaxCountry": "876",
  "TaxDeterminationDate": "2009-06-27",
  "StockType": "6",
  "PurchasingInfoRecordUpdateCode": "6",
  "PriceIsToBePrinted": true,
  "PurchasingPriceIsEstimated": true,
  "NoDaysReminder1": 329,
  "NoDaysReminder2": 382,
  "NoDaysReminder3": 239,
  "PlannedDeliveryDurationInDays": 219,
  "OverdelivTolrtdLmtRatioInPct": 814.3,
  "UnlimitedOverdeliveryIsAllowed": true,
  "UnderdelivTolrtdLmtRatioInPct": 159.3,
  "PurchasingDocumentItemCategory": "6",
  "AccountAssignmentCategory": "6",
  "MultipleAcctAssgmtDistribution": "6",
  "GoodsReceiptIsExpected": true,
  "GoodsReceiptIsNonValuated": true,
  "InvoiceIsExpected": true,
  "InvoiceIsGoodsReceiptBased": true,
  "IsOrderAcknRqd": true,
  "PurgDocOrderAcknNumber": "erAcknNumber-8676876",
  "ShippingInstruction": "76",
  "ManualDeliveryAddressID": "ID-8676876",
  "VolumeUnit": "876",
  "PurContrVolumeUnitISOCode": "876",
  "IncotermsClassification": "876",
  "Subcontractor": "or-8676876",
  "EvaldRcptSettlmtIsAllowed": true,
  "IncotermsLocation1": "IncotermsLocation1-8676876",
  "IncotermsLocation2": "IncotermsLocation2-8676876",
  "IncotermsLocation1Identifier": "n1Identifier-8676876",
  "IncotermsLocation2Identifier": "n2Identifier-8676876",
  "Material": "Material-8676876",
  "ServicePerformer": "er-8676876",
  "ProductTypeCode": "76",
  "MaterialType": "6876",
  "PurContractItmReplnmtElmntType": "6",
  "PurContrAcceptedAtOriginCode": "6",
  "PurgProdCmplncSupplierStatus": "6",
  "PurchaseContractItemFormatted": "rmatted-8676876",
  "PurchasingParentItem": "76876",
  "PurgDocItemCatalogRelevance": "6",
  "ContractConsumptionInPct": 29732424.548,
  "to_PurContrItemCndnValdty": [
    {
      "PurchaseContract": "ty-8429951",
      "PurchaseContractItem": "29951",
      "ConditionRecord": "ty-8429951",
      "ConditionValidityEndDate": "2008-03-29",
      "ConditionApplication": "51",
      "ConditionType": "9951",
      "ConditionIsDeleted": false,
      "Plant": "9951",
      "ConditionValidityStartDate": "2016-03-01",
      "to_PurchaseContractItem": {
        "PurchaseContract": "em-8676876",
        "PurchaseContractItem": "76876"
      },
      "to_PurchaseContract": {
        "PurchaseContract": "t-14594454"
      },
      "to_PurContrItmCndnAmount": [
        {
          "PurchaseContract": "t-24653536",
          "PurchaseContractItem": "53536",
          "ConditionRecord": "t-24653536",
          "ConditionValidityEndDate": "2000-10-06",
          "ConditionSequentialNumber": "36",
          "ConditionValidityStartDate": "2019-12-24",
          "Plant": "3536",
          "ConditionType": "3536",
          "ConditionTextID": "D-24653536",
          "ConditionCalculationType": "6",
          "ConditionRateRatioUnit": "536",
          "PurContrCndnRateRatioUntISOCd": "536",
          "ConditionRateRatio": 12144266.20380983,
          "ConditionCurrency": "53536",
          "ConditionRateAmount": 5884731.22668625,
          "ConditionRateValue": 279021.256,
          "ConditionRateValueUnit": "53536",
          "ConditionQuantity": 44303,
          "ConditionQuantityUnit": "536",
          "PurContrCndnQtyUnitISOCode": "536",
          "ConditionToBaseQtyNmrtr": 23929,
          "ConditionToBaseQtyDnmntr": 47233,
          "BaseUnit": "536",
          "PurContrBaseUnitISOCode": "536",
          "ConditionLowerLimitAmount": 23639647.6982526,
          "ConditionLowerLimitRatio": 24518801.4218701,
          "ConditionUpperLimitAmount": 3241247.10394176,
          "ConditionUpperLimitRatio": 8209023.12174779,
          "ConditionAlternativeCurrency": "53536",
          "ConditionExclusion": "6",
          "ConditionIsDeleted": true,
          "AdditionalValueDays": "36",
          "FixedValueDate": "2016-01-02",
          "PaymentTerms": "3536",
          "CndnMaxNumberOfSalesOrders": "36",
          "MinimumConditionBasisValue": 23269029.177,
          "MaximumConditionBasisValue": 9015073.161,
          "MaximumConditionAmount": 15837738.184,
          "ConditionReleaseStatus": "6",
          "ConditionChangeReason": "536",
          "PricingScaleType": "6",
          "PricingScaleBasis": "6",
          "PricingScaleLine": "3536",
          "ConditionHasScales": true,
          "PricingScaleCheckingRule": "6",
          "to_PurchaseContract": {
            "PurchaseContract": "t-14594454"
          },
          "to_PurContrItmCndnScales": [
            {
              "PurchaseContract": "s-24380169",
              "PurchaseContractItem": "80169",
              "ConditionRecord": "s-24380169",
              "ConditionSequentialNumber": "69",
              "ConditionValidityEndDate": "2003-06-12",
              "ConditionScaleLine": "0169",
              "ConditionScaleQuantity": 6947120.201,
              "ConditionScaleQuantityUnit": "169",
              "PurContrCndnScQtyUnitISOCode": "169",
              "ConditionScaleAmount": 166324.189,
              "ConditionScaleAmountCurrency": "80169",
              "ConditionRateValue": 16054935.317,
              "ConditionRateValueUnit": "80169",
              "ConditionRateRatio": 15701505.25703206,
              "ConditionRateRatioUnit": "169",
              "PurContrCndnRateRatioUntISOCd": "169",
              "ConditionRateAmount": 26826142.29404152,
              "ConditionCurrency": "80169",
              "ConditionScaleIsDeleted": false,
              "PricingScaleType": "9",
              "ConditionQuantity": 25274,
              "ConditionQuantityUnit": "169",
              "PurContrCndnQtyUnitISOCode": "169",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            },
            {
              "PurchaseContract": "s-24380170",
              "PurchaseContractItem": "80170",
              "ConditionRecord": "s-24380170",
              "ConditionSequentialNumber": "70",
              "ConditionValidityEndDate": "2014-12-27",
              "ConditionScaleLine": "0170",
              "ConditionScaleQuantity": 21499206.168,
              "ConditionScaleQuantityUnit": "170",
              "PurContrCndnScQtyUnitISOCode": "170",
              "ConditionScaleAmount": 18169557.926,
              "ConditionScaleAmountCurrency": "80170",
              "ConditionRateValue": 6940931.199,
              "ConditionRateValueUnit": "80170",
              "ConditionRateRatio": 1708841.25955727,
              "ConditionRateRatioUnit": "170",
              "PurContrCndnRateRatioUntISOCd": "170",
              "ConditionRateAmount": 7384680.6115216,
              "ConditionCurrency": "80170",
              "ConditionScaleIsDeleted": true,
              "PricingScaleType": "0",
              "ConditionQuantity": 27855,
              "ConditionQuantityUnit": "170",
              "PurContrCndnQtyUnitISOCode": "170",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            }
          ]
        },
        {
          "PurchaseContract": "t-24653537",
          "PurchaseContractItem": "53537",
          "ConditionRecord": "t-24653537",
          "ConditionValidityEndDate": "2016-08-11",
          "ConditionSequentialNumber": "37",
          "ConditionValidityStartDate": "2019-03-21",
          "Plant": "3537",
          "ConditionType": "3537",
          "ConditionTextID": "D-24653537",
          "ConditionCalculationType": "7",
          "ConditionRateRatioUnit": "537",
          "PurContrCndnRateRatioUntISOCd": "537",
          "ConditionRateRatio": 1020701.481945,
          "ConditionCurrency": "53537",
          "ConditionRateAmount": 12379971.205252,
          "ConditionRateValue": 15321981.208,
          "ConditionRateValueUnit": "53537",
          "ConditionQuantity": 24526,
          "ConditionQuantityUnit": "537",
          "PurContrCndnQtyUnitISOCode": "537",
          "ConditionToBaseQtyNmrtr": 90820,
          "ConditionToBaseQtyDnmntr": 50005,
          "BaseUnit": "537",
          "PurContrBaseUnitISOCode": "537",
          "ConditionLowerLimitAmount": 29367725.2449267,
          "ConditionLowerLimitRatio": 31715338.5839903,
          "ConditionUpperLimitAmount": 30528666.30055332,
          "ConditionUpperLimitRatio": 1760164.27163823,
          "ConditionAlternativeCurrency": "53537",
          "ConditionExclusion": "7",
          "ConditionIsDeleted": false,
          "AdditionalValueDays": "37",
          "FixedValueDate": "2022-02-24",
          "PaymentTerms": "3537",
          "CndnMaxNumberOfSalesOrders": "37",
          "MinimumConditionBasisValue": 24286732.289,
          "MaximumConditionBasisValue": 28296490.37,
          "MaximumConditionAmount": 26534634.789,
          "ConditionReleaseStatus": "7",
          "ConditionChangeReason": "537",
          "PricingScaleType": "7",
          "PricingScaleBasis": "7",
          "PricingScaleLine": "3537",
          "ConditionHasScales": false,
          "PricingScaleCheckingRule": "7",
          "to_PurchaseContract": {
            "PurchaseContract": "t-14594454"
          },
          "to_PurContrItmCndnScales": [
            {
              "PurchaseContract": "es-6684359",
              "PurchaseContractItem": "84359",
              "ConditionRecord": "es-6684359",
              "ConditionSequentialNumber": "59",
              "ConditionValidityEndDate": "2007-06-02",
              "ConditionScaleLine": "4359",
              "ConditionScaleQuantity": 20862741.116,
              "ConditionScaleQuantityUnit": "359",
              "PurContrCndnScQtyUnitISOCode": "359",
              "ConditionScaleAmount": 4327153.201,
              "ConditionScaleAmountCurrency": "84359",
              "ConditionRateValue": 24738677.28,
              "ConditionRateValueUnit": "84359",
              "ConditionRateRatio": 7660030.17337279,
              "ConditionRateRatioUnit": "359",
              "PurContrCndnRateRatioUntISOCd": "359",
              "ConditionRateAmount": 19676903.16329078,
              "ConditionCurrency": "84359",
              "ConditionScaleIsDeleted": false,
              "PricingScaleType": "9",
              "ConditionQuantity": 32735,
              "ConditionQuantityUnit": "359",
              "PurContrCndnQtyUnitISOCode": "359",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            },
            {
              "PurchaseContract": "es-6684360",
              "PurchaseContractItem": "84360",
              "ConditionRecord": "es-6684360",
              "ConditionSequentialNumber": "60",
              "ConditionValidityEndDate": "2015-01-12",
              "ConditionScaleLine": "4360",
              "ConditionScaleQuantity": 28641209.249,
              "ConditionScaleQuantityUnit": "360",
              "PurContrCndnScQtyUnitISOCode": "360",
              "ConditionScaleAmount": 30822267.109,
              "ConditionScaleAmountCurrency": "84360",
              "ConditionRateValue": 25306080.316,
              "ConditionRateValueUnit": "84360",
              "ConditionRateRatio": 16413151.29062462,
              "ConditionRateRatioUnit": "360",
              "PurContrCndnRateRatioUntISOCd": "360",
              "ConditionRateAmount": 935006.2665566,
              "ConditionCurrency": "84360",
              "ConditionScaleIsDeleted": true,
              "PricingScaleType": "0",
              "ConditionQuantity": 52208,
              "ConditionQuantityUnit": "360",
              "PurContrCndnQtyUnitISOCode": "360",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            }
          ]
        }
      ]
    },
    {
      "PurchaseContract": "ty-8429952",
      "PurchaseContractItem": "29952",
      "ConditionRecord": "ty-8429952",
      "ConditionValidityEndDate": "2016-10-14",
      "ConditionApplication": "52",
      "ConditionType": "9952",
      "ConditionIsDeleted": true,
      "Plant": "9952",
      "ConditionValidityStartDate": "2015-08-15",
      "to_PurchaseContractItem": {
        "PurchaseContract": "em-8676876",
        "PurchaseContractItem": "76876"
      },
      "to_PurchaseContract": {
        "PurchaseContract": "t-14594454"
      },
      "to_PurContrItmCndnAmount": [
        {
          "PurchaseContract": "t-20605109",
          "PurchaseContractItem": "05109",
          "ConditionRecord": "t-20605109",
          "ConditionValidityEndDate": "2006-11-01",
          "ConditionSequentialNumber": "09",
          "ConditionValidityStartDate": "2020-07-26",
          "Plant": "5109",
          "ConditionType": "5109",
          "ConditionTextID": "D-20605109",
          "ConditionCalculationType": "9",
          "ConditionRateRatioUnit": "109",
          "PurContrCndnRateRatioUntISOCd": "109",
          "ConditionRateRatio": 13450867.92044,
          "ConditionCurrency": "05109",
          "ConditionRateAmount": 19795518.2191162,
          "ConditionRateValue": 28932236.158,
          "ConditionRateValueUnit": "05109",
          "ConditionQuantity": 10482,
          "ConditionQuantityUnit": "109",
          "PurContrCndnQtyUnitISOCode": "109",
          "ConditionToBaseQtyNmrtr": 63026,
          "ConditionToBaseQtyDnmntr": 65584,
          "BaseUnit": "109",
          "PurContrBaseUnitISOCode": "109",
          "ConditionLowerLimitAmount": 6572060.8225014,
          "ConditionLowerLimitRatio": 24871736.18905018,
          "ConditionUpperLimitAmount": 8091772.28376184,
          "ConditionUpperLimitRatio": 22940411.24281006,
          "ConditionAlternativeCurrency": "05109",
          "ConditionExclusion": "9",
          "ConditionIsDeleted": false,
          "AdditionalValueDays": "09",
          "FixedValueDate": "2023-01-24",
          "PaymentTerms": "5109",
          "CndnMaxNumberOfSalesOrders": "09",
          "MinimumConditionBasisValue": 23814901.174,
          "MaximumConditionBasisValue": 10091506.617,
          "MaximumConditionAmount": 17676595.277,
          "ConditionReleaseStatus": "9",
          "ConditionChangeReason": "109",
          "PricingScaleType": "9",
          "PricingScaleBasis": "9",
          "PricingScaleLine": "5109",
          "ConditionHasScales": false,
          "PricingScaleCheckingRule": "9",
          "to_PurchaseContract": {
            "PurchaseContract": "t-14594454"
          },
          "to_PurContrItmCndnScales": [
            {
              "PurchaseContract": "es-9167962",
              "PurchaseContractItem": "67962",
              "ConditionRecord": "es-9167962",
              "ConditionSequentialNumber": "62",
              "ConditionValidityEndDate": "2015-10-20",
              "ConditionScaleLine": "7962",
              "ConditionScaleQuantity": 26906533.179,
              "ConditionScaleQuantityUnit": "962",
              "PurContrCndnScQtyUnitISOCode": "962",
              "ConditionScaleAmount": 6634879.265,
              "ConditionScaleAmountCurrency": "67962",
              "ConditionRateValue": 9654614.253,
              "ConditionRateValueUnit": "67962",
              "ConditionRateRatio": 31447484.1852617,
              "ConditionRateRatioUnit": "962",
              "PurContrCndnRateRatioUntISOCd": "962",
              "ConditionRateAmount": 16547642.12435741,
              "ConditionCurrency": "67962",
              "ConditionScaleIsDeleted": true,
              "PricingScaleType": "2",
              "ConditionQuantity": 1425,
              "ConditionQuantityUnit": "962",
              "PurContrCndnQtyUnitISOCode": "962",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            },
            {
              "PurchaseContract": "es-9167963",
              "PurchaseContractItem": "67963",
              "ConditionRecord": "es-9167963",
              "ConditionSequentialNumber": "63",
              "ConditionValidityEndDate": "2008-09-08",
              "ConditionScaleLine": "7963",
              "ConditionScaleQuantity": 21278002.694,
              "ConditionScaleQuantityUnit": "963",
              "PurContrCndnScQtyUnitISOCode": "963",
              "ConditionScaleAmount": 1545248.159,
              "ConditionScaleAmountCurrency": "67963",
              "ConditionRateValue": 14165268.179,
              "ConditionRateValueUnit": "67963",
              "ConditionRateRatio": 27216944.719933,
              "ConditionRateRatioUnit": "963",
              "PurContrCndnRateRatioUntISOCd": "963",
              "ConditionRateAmount": 12153286.28173042,
              "ConditionCurrency": "67963",
              "ConditionScaleIsDeleted": false,
              "PricingScaleType": "3",
              "ConditionQuantity": 23280,
              "ConditionQuantityUnit": "963",
              "PurContrCndnQtyUnitISOCode": "963",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            }
          ]
        },
        {
          "PurchaseContract": "t-20605110",
          "PurchaseContractItem": "05110",
          "ConditionRecord": "t-20605110",
          "ConditionValidityEndDate": "2010-01-19",
          "ConditionSequentialNumber": "10",
          "ConditionValidityStartDate": "2012-02-29",
          "Plant": "5110",
          "ConditionType": "5110",
          "ConditionTextID": "D-20605110",
          "ConditionCalculationType": "0",
          "ConditionRateRatioUnit": "110",
          "PurContrCndnRateRatioUntISOCd": "110",
          "ConditionRateRatio": 26251340.17031381,
          "ConditionCurrency": "05110",
          "ConditionRateAmount": 13178576.575772,
          "ConditionRateValue": 11389792.262,
          "ConditionRateValueUnit": "05110",
          "ConditionQuantity": 83082,
          "ConditionQuantityUnit": "110",
          "PurContrCndnQtyUnitISOCode": "110",
          "ConditionToBaseQtyNmrtr": 86398,
          "ConditionToBaseQtyDnmntr": 55593,
          "BaseUnit": "110",
          "PurContrBaseUnitISOCode": "110",
          "ConditionLowerLimitAmount": 30698197.9139259,
          "ConditionLowerLimitRatio": 21267529.16451564,
          "ConditionUpperLimitAmount": 17844467.15395563,
          "ConditionUpperLimitRatio": 19061507.18534103,
          "ConditionAlternativeCurrency": "05110",
          "ConditionExclusion": "0",
          "ConditionIsDeleted": true,
          "AdditionalValueDays": "10",
          "FixedValueDate": "2015-08-01",
          "PaymentTerms": "5110",
          "CndnMaxNumberOfSalesOrders": "10",
          "MinimumConditionBasisValue": 13958453.209,
          "MaximumConditionBasisValue": 26462985.189,
          "MaximumConditionAmount": 18951324.208,
          "ConditionReleaseStatus": "0",
          "ConditionChangeReason": "110",
          "PricingScaleType": "0",
          "PricingScaleBasis": "0",
          "PricingScaleLine": "5110",
          "ConditionHasScales": true,
          "PricingScaleCheckingRule": "0",
          "to_PurchaseContract": {
            "PurchaseContract": "t-14594454"
          },
          "to_PurContrItmCndnScales": [
            {
              "PurchaseContract": "s-25840653",
              "PurchaseContractItem": "40653",
              "ConditionRecord": "s-25840653",
              "ConditionSequentialNumber": "53",
              "ConditionValidityEndDate": "2002-04-01",
              "ConditionScaleLine": "0653",
              "ConditionScaleQuantity": 7636621.17,
              "ConditionScaleQuantityUnit": "653",
              "PurContrCndnScQtyUnitISOCode": "653",
              "ConditionScaleAmount": 16121869.559,
              "ConditionScaleAmountCurrency": "40653",
              "ConditionRateValue": 2055822.305,
              "ConditionRateValueUnit": "40653",
              "ConditionRateRatio": 7589820.3301014,
              "ConditionRateRatioUnit": "653",
              "PurContrCndnRateRatioUntISOCd": "653",
              "ConditionRateAmount": 23281598.28883497,
              "ConditionCurrency": "40653",
              "ConditionScaleIsDeleted": false,
              "PricingScaleType": "3",
              "ConditionQuantity": 62424,
              "ConditionQuantityUnit": "653",
              "PurContrCndnQtyUnitISOCode": "653",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            },
            {
              "PurchaseContract": "s-25840654",
              "PurchaseContractItem": "40654",
              "ConditionRecord": "s-25840654",
              "ConditionSequentialNumber": "54",
              "ConditionValidityEndDate": "2021-02-15",
              "ConditionScaleLine": "0654",
              "ConditionScaleQuantity": 27568892.307,
              "ConditionScaleQuantityUnit": "654",
              "PurContrCndnScQtyUnitISOCode": "654",
              "ConditionScaleAmount": 3260093.804,
              "ConditionScaleAmountCurrency": "40654",
              "ConditionRateValue": 10831701.398,
              "ConditionRateValueUnit": "40654",
              "ConditionRateRatio": 7461253.843177,
              "ConditionRateRatioUnit": "654",
              "PurContrCndnRateRatioUntISOCd": "654",
              "ConditionRateAmount": 783027.21601694,
              "ConditionCurrency": "40654",
              "ConditionScaleIsDeleted": true,
              "PricingScaleType": "4",
              "ConditionQuantity": 79769,
              "ConditionQuantityUnit": "654",
              "PurContrCndnQtyUnitISOCode": "654",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            }
          ]
        }
      ]
    }
  ],
  "to_PurCtrAccount": [
    {
      "AccountAssignment": "A_PurCtrAccount-19286112",
      "PurchaseContractItem": "86112",
      "PurchaseContract": "t-19286112",
      "IsDeleted": true,
      "Quantity": 30457791.143,
      "OrderQuantityUnit": "112",
      "OrderQuantityUnitISOCode": "112",
      "MultipleAcctAssgmtDistrPercent": 534.2,
      "PurgDocNetAmount": 26844154.305,
      "DocumentCurrency": "86112",
      "GLAccount": "t-19286112",
      "BusinessArea": "6112",
      "CostCenter": "r-19286112",
      "SalesOrder": "r-19286112",
      "SalesOrderItem": "286112",
      "SalesOrderScheduleLine": "6112",
      "MasterFixedAsset": "set-19286112",
      "FixedAsset": "6112",
      "OrderID": "rID-19286112",
      "GoodsRecipientName": "ame-19286112",
      "UnloadingPointName": "loadingPointName-19286112",
      "ControllingArea": "6112",
      "CostObject": "ect-19286112",
      "ProfitCenter": "r-19286112",
      "ProjectNetwork": "ork-19286112",
      "RealEstateObject": "19286112",
      "PartnerAccountNumber": "r-19286112",
      "CommitmentItem": "CommitmentItem-19286112",
      "JointVentureRecoveryCode": "12",
      "FundsCenter": "sCenter-19286112",
      "FunctionalArea": "nalArea-19286112",
      "SettlementReferenceDate": "2005-08-16",
      "TaxCode": "12",
      "TaxJurisdiction": "iction-19286112",
      "NonDeductibleInputTaxAmount": 26571123.699,
      "CostCtrActivityType": "286112",
      "BusinessProcess": "ess-19286112",
      "EarmarkedFundsDocument": "t-19286112",
      "GrantID": "GrantID-19286112",
      "BudgetPeriod": "d-19286112",
      "WBSElementExternalID": "ementExternalID-19286112"
    },
    {
      "AccountAssignment": "A_PurCtrAccount-19286113",
      "PurchaseContractItem": "86113",
      "PurchaseContract": "t-19286113",
      "IsDeleted": false,
      "Quantity": 15505842.238,
      "OrderQuantityUnit": "113",
      "OrderQuantityUnitISOCode": "113",
      "MultipleAcctAssgmtDistrPercent": 532.3,
      "PurgDocNetAmount": 12933403.532,
      "DocumentCurrency": "86113",
      "GLAccount": "t-19286113",
      "BusinessArea": "6113",
      "CostCenter": "r-19286113",
      "SalesOrder": "r-19286113",
      "SalesOrderItem": "286113",
      "SalesOrderScheduleLine": "6113",
      "MasterFixedAsset": "set-19286113",
      "FixedAsset": "6113",
      "OrderID": "rID-19286113",
      "GoodsRecipientName": "ame-19286113",
      "UnloadingPointName": "loadingPointName-19286113",
      "ControllingArea": "6113",
      "CostObject": "ect-19286113",
      "ProfitCenter": "r-19286113",
      "ProjectNetwork": "ork-19286113",
      "RealEstateObject": "19286113",
      "PartnerAccountNumber": "r-19286113",
      "CommitmentItem": "CommitmentItem-19286113",
      "JointVentureRecoveryCode": "13",
      "FundsCenter": "sCenter-19286113",
      "FunctionalArea": "nalArea-19286113",
      "SettlementReferenceDate": "2009-05-10",
      "TaxCode": "13",
      "TaxJurisdiction": "iction-19286113",
      "NonDeductibleInputTaxAmount": 30764946.469,
      "CostCtrActivityType": "286113",
      "BusinessProcess": "ess-19286113",
      "EarmarkedFundsDocument": "t-19286113",
      "GrantID": "GrantID-19286113",
      "BudgetPeriod": "d-19286113",
      "WBSElementExternalID": "ementExternalID-19286113"
    }
  ],
  "to_PurCtrAddress": [
    {
      "PurchaseContract": "ss-2579503",
      "AddressID": "ss-2579503",
      "PurchaseContractItem": "79503",
      "FormOfAddress": "9503",
      "FullName": "FullName-2579503",
      "ConsigneeName3": "ConsigneeName3-2579503",
      "ConsigneeName4": "ConsigneeName4-2579503",
      "CareOfName": "CareOfName-2579503",
      "CityName": "CityName-2579503",
      "District": "District-2579503",
      "CityCode": "9503",
      "PostalCode": "de-2579503",
      "POBoxPostalCode": "de-2579503",
      "CompanyPostalCode": "de-2579503",
      "POBox": "ox-2579503",
      "POBoxDeviatingCityName": "POBoxDeviatingCityName-2579503",
      "StreetName": "StreetName-2579503",
      "HouseNumber": "er-2579503",
      "StreetPrefixName": "StreetPrefixName-2579503",
      "AdditionalStreetPrefixName": "AdditionalStreetPrefixName-2579503",
      "AdditionalStreetSuffixName": "AdditionalStreetSuffixName-2579503",
      "Building": "Building-2579503",
      "Floor": "or-2579503",
      "RoomNumber": "er-2579503",
      "Country": "503",
      "CorrespondenceLanguage": "03",
      "Region": "503",
      "AddressTimeZone": "579503",
      "TaxJurisdiction": "diction-2579503",
      "PrfrdCommMediumType": "503",
      "PhoneNumber": "PhoneNumber-2579503",
      "FaxNumber": "FaxNumber-2579503",
      "TransportZone": "ne-2579503",
      "HouseNumberSupplementText": "xt-2579503",
      "StreetSuffixName": "StreetSuffixName-2579503"
    },
    {
      "PurchaseContract": "ss-2579504",
      "AddressID": "ss-2579504",
      "PurchaseContractItem": "79504",
      "FormOfAddress": "9504",
      "FullName": "FullName-2579504",
      "ConsigneeName3": "ConsigneeName3-2579504",
      "ConsigneeName4": "ConsigneeName4-2579504",
      "CareOfName": "CareOfName-2579504",
      "CityName": "CityName-2579504",
      "District": "District-2579504",
      "CityCode": "9504",
      "PostalCode": "de-2579504",
      "POBoxPostalCode": "de-2579504",
      "CompanyPostalCode": "de-2579504",
      "POBox": "ox-2579504",
      "POBoxDeviatingCityName": "POBoxDeviatingCityName-2579504",
      "StreetName": "StreetName-2579504",
      "HouseNumber": "er-2579504",
      "StreetPrefixName": "StreetPrefixName-2579504",
      "AdditionalStreetPrefixName": "AdditionalStreetPrefixName-2579504",
      "AdditionalStreetSuffixName": "AdditionalStreetSuffixName-2579504",
      "Building": "Building-2579504",
      "Floor": "or-2579504",
      "RoomNumber": "er-2579504",
      "Country": "504",
      "CorrespondenceLanguage": "04",
      "Region": "504",
      "AddressTimeZone": "579504",
      "TaxJurisdiction": "diction-2579504",
      "PrfrdCommMediumType": "504",
      "PhoneNumber": "PhoneNumber-2579504",
      "FaxNumber": "FaxNumber-2579504",
      "TransportZone": "ne-2579504",
      "HouseNumberSupplementText": "xt-2579504",
      "StreetSuffixName": "StreetSuffixName-2579504"
    }
  ],
  "to_PurCtrItemNotes": [
    {
      "Language": "09",
      "TextObjectType": "0809",
      "ArchitecturalObjectNumber": "A_PurchaseContractItemNotes-30740809",
      "TechnicalObjectType": "s-30740809",
      "PurchaseContractItem": "40809",
      "PurchaseContract": "s-30740809",
      "NoteDescription": "NoteDescription-30740809",
      "FixedIndicator": "9"
    },
    {
      "Language": "10",
      "TextObjectType": "0810",
      "ArchitecturalObjectNumber": "A_PurchaseContractItemNotes-30740810",
      "TechnicalObjectType": "s-30740810",
      "PurchaseContractItem": "40810",
      "PurchaseContract": "s-30740810",
      "NoteDescription": "NoteDescription-30740810",
      "FixedIndicator": "0"
    }
  ],
  "to_PurchaseContract": {
    "PurchaseContract": "t-14594454"
  }
}


### A_PurchaseContractItem
# @name A_PurchaseContractItem_PATCH
PATCH {{server}}/proxy/A_PurchaseContractItem(PurchaseContract='em-8676876',PurchaseContractItem='76876')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "PurchaseContract": "em-8676876",
  "PurchaseContractItem": "76876",
  "PurchasingContractDeletionCode": "6",
  "PurchaseContractItemText": "PurchaseContractItemText-8676876",
  "CompanyCode": "6876",
  "Plant": "6876",
  "StorageLocation": "6876",
  "RequirementTracking": "ng-8676876",
  "MaterialGroup": "p-8676876",
  "SupplierMaterialNumber": "SupplierMaterialNumber-8676876",
  "OrderQuantityUnit": "876",
  "OrderQuantityUnitISOCode": "876",
  "TargetQuantity": 24169220.239,
  "PurgDocReleaseOrderQuantity": 15239752.266,
  "OrderPriceUnit": "876",
  "OrderPriceUnitISOCode": "876",
  "OrderPriceUnitToOrderUnitNmrtr": 92250,
  "OrdPriceUnitToOrderUnitDnmntr": 32446,
  "ContractNetPriceAmount": 16349830.795,
  "DocumentCurrency": "76876",
  "NetPriceQuantity": 53292,
  "TaxCode": "76",
  "TaxCountry": "876",
  "TaxDeterminationDate": "2009-06-27",
  "StockType": "6",
  "PurchasingInfoRecordUpdateCode": "6",
  "PriceIsToBePrinted": true,
  "PurchasingPriceIsEstimated": true,
  "NoDaysReminder1": 329,
  "NoDaysReminder2": 382,
  "NoDaysReminder3": 239,
  "PlannedDeliveryDurationInDays": 219,
  "OverdelivTolrtdLmtRatioInPct": 814.3,
  "UnlimitedOverdeliveryIsAllowed": true,
  "UnderdelivTolrtdLmtRatioInPct": 159.3,
  "PurchasingDocumentItemCategory": "6",
  "AccountAssignmentCategory": "6",
  "MultipleAcctAssgmtDistribution": "6",
  "GoodsReceiptIsExpected": true,
  "GoodsReceiptIsNonValuated": true,
  "InvoiceIsExpected": true,
  "InvoiceIsGoodsReceiptBased": true,
  "IsOrderAcknRqd": true,
  "PurgDocOrderAcknNumber": "erAcknNumber-8676876",
  "ShippingInstruction": "76",
  "ManualDeliveryAddressID": "ID-8676876",
  "VolumeUnit": "876",
  "PurContrVolumeUnitISOCode": "876",
  "IncotermsClassification": "876",
  "Subcontractor": "or-8676876",
  "EvaldRcptSettlmtIsAllowed": true,
  "IncotermsLocation1": "IncotermsLocation1-8676876",
  "IncotermsLocation2": "IncotermsLocation2-8676876",
  "IncotermsLocation1Identifier": "n1Identifier-8676876",
  "IncotermsLocation2Identifier": "n2Identifier-8676876",
  "Material": "Material-8676876",
  "ServicePerformer": "er-8676876",
  "ProductTypeCode": "76",
  "MaterialType": "6876",
  "PurContractItmReplnmtElmntType": "6",
  "PurContrAcceptedAtOriginCode": "6",
  "PurgProdCmplncSupplierStatus": "6",
  "PurchaseContractItemFormatted": "rmatted-8676876",
  "PurchasingParentItem": "76876",
  "PurgDocItemCatalogRelevance": "6",
  "ContractConsumptionInPct": 29732424.548,
  "to_PurContrItemCndnValdty": [
    {
      "PurchaseContract": "ty-8429951",
      "PurchaseContractItem": "29951",
      "ConditionRecord": "ty-8429951",
      "ConditionValidityEndDate": "2008-03-29",
      "ConditionApplication": "51",
      "ConditionType": "9951",
      "ConditionIsDeleted": false,
      "Plant": "9951",
      "ConditionValidityStartDate": "2016-03-01",
      "to_PurchaseContractItem": {
        "PurchaseContract": "em-8676876",
        "PurchaseContractItem": "76876"
      },
      "to_PurchaseContract": {
        "PurchaseContract": "t-14594454"
      },
      "to_PurContrItmCndnAmount": [
        {
          "PurchaseContract": "t-24653536",
          "PurchaseContractItem": "53536",
          "ConditionRecord": "t-24653536",
          "ConditionValidityEndDate": "2000-10-06",
          "ConditionSequentialNumber": "36",
          "ConditionValidityStartDate": "2019-12-24",
          "Plant": "3536",
          "ConditionType": "3536",
          "ConditionTextID": "D-24653536",
          "ConditionCalculationType": "6",
          "ConditionRateRatioUnit": "536",
          "PurContrCndnRateRatioUntISOCd": "536",
          "ConditionRateRatio": 12144266.20380983,
          "ConditionCurrency": "53536",
          "ConditionRateAmount": 5884731.22668625,
          "ConditionRateValue": 279021.256,
          "ConditionRateValueUnit": "53536",
          "ConditionQuantity": 44303,
          "ConditionQuantityUnit": "536",
          "PurContrCndnQtyUnitISOCode": "536",
          "ConditionToBaseQtyNmrtr": 23929,
          "ConditionToBaseQtyDnmntr": 47233,
          "BaseUnit": "536",
          "PurContrBaseUnitISOCode": "536",
          "ConditionLowerLimitAmount": 23639647.6982526,
          "ConditionLowerLimitRatio": 24518801.4218701,
          "ConditionUpperLimitAmount": 3241247.10394176,
          "ConditionUpperLimitRatio": 8209023.12174779,
          "ConditionAlternativeCurrency": "53536",
          "ConditionExclusion": "6",
          "ConditionIsDeleted": true,
          "AdditionalValueDays": "36",
          "FixedValueDate": "2016-01-02",
          "PaymentTerms": "3536",
          "CndnMaxNumberOfSalesOrders": "36",
          "MinimumConditionBasisValue": 23269029.177,
          "MaximumConditionBasisValue": 9015073.161,
          "MaximumConditionAmount": 15837738.184,
          "ConditionReleaseStatus": "6",
          "ConditionChangeReason": "536",
          "PricingScaleType": "6",
          "PricingScaleBasis": "6",
          "PricingScaleLine": "3536",
          "ConditionHasScales": true,
          "PricingScaleCheckingRule": "6",
          "to_PurchaseContract": {
            "PurchaseContract": "t-14594454"
          },
          "to_PurContrItmCndnScales": [
            {
              "PurchaseContract": "s-24380169",
              "PurchaseContractItem": "80169",
              "ConditionRecord": "s-24380169",
              "ConditionSequentialNumber": "69",
              "ConditionValidityEndDate": "2003-06-12",
              "ConditionScaleLine": "0169",
              "ConditionScaleQuantity": 6947120.201,
              "ConditionScaleQuantityUnit": "169",
              "PurContrCndnScQtyUnitISOCode": "169",
              "ConditionScaleAmount": 166324.189,
              "ConditionScaleAmountCurrency": "80169",
              "ConditionRateValue": 16054935.317,
              "ConditionRateValueUnit": "80169",
              "ConditionRateRatio": 15701505.25703206,
              "ConditionRateRatioUnit": "169",
              "PurContrCndnRateRatioUntISOCd": "169",
              "ConditionRateAmount": 26826142.29404152,
              "ConditionCurrency": "80169",
              "ConditionScaleIsDeleted": false,
              "PricingScaleType": "9",
              "ConditionQuantity": 25274,
              "ConditionQuantityUnit": "169",
              "PurContrCndnQtyUnitISOCode": "169",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            },
            {
              "PurchaseContract": "s-24380170",
              "PurchaseContractItem": "80170",
              "ConditionRecord": "s-24380170",
              "ConditionSequentialNumber": "70",
              "ConditionValidityEndDate": "2014-12-27",
              "ConditionScaleLine": "0170",
              "ConditionScaleQuantity": 21499206.168,
              "ConditionScaleQuantityUnit": "170",
              "PurContrCndnScQtyUnitISOCode": "170",
              "ConditionScaleAmount": 18169557.926,
              "ConditionScaleAmountCurrency": "80170",
              "ConditionRateValue": 6940931.199,
              "ConditionRateValueUnit": "80170",
              "ConditionRateRatio": 1708841.25955727,
              "ConditionRateRatioUnit": "170",
              "PurContrCndnRateRatioUntISOCd": "170",
              "ConditionRateAmount": 7384680.6115216,
              "ConditionCurrency": "80170",
              "ConditionScaleIsDeleted": true,
              "PricingScaleType": "0",
              "ConditionQuantity": 27855,
              "ConditionQuantityUnit": "170",
              "PurContrCndnQtyUnitISOCode": "170",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            }
          ]
        },
        {
          "PurchaseContract": "t-24653537",
          "PurchaseContractItem": "53537",
          "ConditionRecord": "t-24653537",
          "ConditionValidityEndDate": "2016-08-11",
          "ConditionSequentialNumber": "37",
          "ConditionValidityStartDate": "2019-03-21",
          "Plant": "3537",
          "ConditionType": "3537",
          "ConditionTextID": "D-24653537",
          "ConditionCalculationType": "7",
          "ConditionRateRatioUnit": "537",
          "PurContrCndnRateRatioUntISOCd": "537",
          "ConditionRateRatio": 1020701.481945,
          "ConditionCurrency": "53537",
          "ConditionRateAmount": 12379971.205252,
          "ConditionRateValue": 15321981.208,
          "ConditionRateValueUnit": "53537",
          "ConditionQuantity": 24526,
          "ConditionQuantityUnit": "537",
          "PurContrCndnQtyUnitISOCode": "537",
          "ConditionToBaseQtyNmrtr": 90820,
          "ConditionToBaseQtyDnmntr": 50005,
          "BaseUnit": "537",
          "PurContrBaseUnitISOCode": "537",
          "ConditionLowerLimitAmount": 29367725.2449267,
          "ConditionLowerLimitRatio": 31715338.5839903,
          "ConditionUpperLimitAmount": 30528666.30055332,
          "ConditionUpperLimitRatio": 1760164.27163823,
          "ConditionAlternativeCurrency": "53537",
          "ConditionExclusion": "7",
          "ConditionIsDeleted": false,
          "AdditionalValueDays": "37",
          "FixedValueDate": "2022-02-24",
          "PaymentTerms": "3537",
          "CndnMaxNumberOfSalesOrders": "37",
          "MinimumConditionBasisValue": 24286732.289,
          "MaximumConditionBasisValue": 28296490.37,
          "MaximumConditionAmount": 26534634.789,
          "ConditionReleaseStatus": "7",
          "ConditionChangeReason": "537",
          "PricingScaleType": "7",
          "PricingScaleBasis": "7",
          "PricingScaleLine": "3537",
          "ConditionHasScales": false,
          "PricingScaleCheckingRule": "7",
          "to_PurchaseContract": {
            "PurchaseContract": "t-14594454"
          },
          "to_PurContrItmCndnScales": [
            {
              "PurchaseContract": "es-6684359",
              "PurchaseContractItem": "84359",
              "ConditionRecord": "es-6684359",
              "ConditionSequentialNumber": "59",
              "ConditionValidityEndDate": "2007-06-02",
              "ConditionScaleLine": "4359",
              "ConditionScaleQuantity": 20862741.116,
              "ConditionScaleQuantityUnit": "359",
              "PurContrCndnScQtyUnitISOCode": "359",
              "ConditionScaleAmount": 4327153.201,
              "ConditionScaleAmountCurrency": "84359",
              "ConditionRateValue": 24738677.28,
              "ConditionRateValueUnit": "84359",
              "ConditionRateRatio": 7660030.17337279,
              "ConditionRateRatioUnit": "359",
              "PurContrCndnRateRatioUntISOCd": "359",
              "ConditionRateAmount": 19676903.16329078,
              "ConditionCurrency": "84359",
              "ConditionScaleIsDeleted": false,
              "PricingScaleType": "9",
              "ConditionQuantity": 32735,
              "ConditionQuantityUnit": "359",
              "PurContrCndnQtyUnitISOCode": "359",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            },
            {
              "PurchaseContract": "es-6684360",
              "PurchaseContractItem": "84360",
              "ConditionRecord": "es-6684360",
              "ConditionSequentialNumber": "60",
              "ConditionValidityEndDate": "2015-01-12",
              "ConditionScaleLine": "4360",
              "ConditionScaleQuantity": 28641209.249,
              "ConditionScaleQuantityUnit": "360",
              "PurContrCndnScQtyUnitISOCode": "360",
              "ConditionScaleAmount": 30822267.109,
              "ConditionScaleAmountCurrency": "84360",
              "ConditionRateValue": 25306080.316,
              "ConditionRateValueUnit": "84360",
              "ConditionRateRatio": 16413151.29062462,
              "ConditionRateRatioUnit": "360",
              "PurContrCndnRateRatioUntISOCd": "360",
              "ConditionRateAmount": 935006.2665566,
              "ConditionCurrency": "84360",
              "ConditionScaleIsDeleted": true,
              "PricingScaleType": "0",
              "ConditionQuantity": 52208,
              "ConditionQuantityUnit": "360",
              "PurContrCndnQtyUnitISOCode": "360",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            }
          ]
        }
      ]
    },
    {
      "PurchaseContract": "ty-8429952",
      "PurchaseContractItem": "29952",
      "ConditionRecord": "ty-8429952",
      "ConditionValidityEndDate": "2016-10-14",
      "ConditionApplication": "52",
      "ConditionType": "9952",
      "ConditionIsDeleted": true,
      "Plant": "9952",
      "ConditionValidityStartDate": "2015-08-15",
      "to_PurchaseContractItem": {
        "PurchaseContract": "em-8676876",
        "PurchaseContractItem": "76876"
      },
      "to_PurchaseContract": {
        "PurchaseContract": "t-14594454"
      },
      "to_PurContrItmCndnAmount": [
        {
          "PurchaseContract": "t-20605109",
          "PurchaseContractItem": "05109",
          "ConditionRecord": "t-20605109",
          "ConditionValidityEndDate": "2006-11-01",
          "ConditionSequentialNumber": "09",
          "ConditionValidityStartDate": "2020-07-26",
          "Plant": "5109",
          "ConditionType": "5109",
          "ConditionTextID": "D-20605109",
          "ConditionCalculationType": "9",
          "ConditionRateRatioUnit": "109",
          "PurContrCndnRateRatioUntISOCd": "109",
          "ConditionRateRatio": 13450867.92044,
          "ConditionCurrency": "05109",
          "ConditionRateAmount": 19795518.2191162,
          "ConditionRateValue": 28932236.158,
          "ConditionRateValueUnit": "05109",
          "ConditionQuantity": 10482,
          "ConditionQuantityUnit": "109",
          "PurContrCndnQtyUnitISOCode": "109",
          "ConditionToBaseQtyNmrtr": 63026,
          "ConditionToBaseQtyDnmntr": 65584,
          "BaseUnit": "109",
          "PurContrBaseUnitISOCode": "109",
          "ConditionLowerLimitAmount": 6572060.8225014,
          "ConditionLowerLimitRatio": 24871736.18905018,
          "ConditionUpperLimitAmount": 8091772.28376184,
          "ConditionUpperLimitRatio": 22940411.24281006,
          "ConditionAlternativeCurrency": "05109",
          "ConditionExclusion": "9",
          "ConditionIsDeleted": false,
          "AdditionalValueDays": "09",
          "FixedValueDate": "2023-01-24",
          "PaymentTerms": "5109",
          "CndnMaxNumberOfSalesOrders": "09",
          "MinimumConditionBasisValue": 23814901.174,
          "MaximumConditionBasisValue": 10091506.617,
          "MaximumConditionAmount": 17676595.277,
          "ConditionReleaseStatus": "9",
          "ConditionChangeReason": "109",
          "PricingScaleType": "9",
          "PricingScaleBasis": "9",
          "PricingScaleLine": "5109",
          "ConditionHasScales": false,
          "PricingScaleCheckingRule": "9",
          "to_PurchaseContract": {
            "PurchaseContract": "t-14594454"
          },
          "to_PurContrItmCndnScales": [
            {
              "PurchaseContract": "es-9167962",
              "PurchaseContractItem": "67962",
              "ConditionRecord": "es-9167962",
              "ConditionSequentialNumber": "62",
              "ConditionValidityEndDate": "2015-10-20",
              "ConditionScaleLine": "7962",
              "ConditionScaleQuantity": 26906533.179,
              "ConditionScaleQuantityUnit": "962",
              "PurContrCndnScQtyUnitISOCode": "962",
              "ConditionScaleAmount": 6634879.265,
              "ConditionScaleAmountCurrency": "67962",
              "ConditionRateValue": 9654614.253,
              "ConditionRateValueUnit": "67962",
              "ConditionRateRatio": 31447484.1852617,
              "ConditionRateRatioUnit": "962",
              "PurContrCndnRateRatioUntISOCd": "962",
              "ConditionRateAmount": 16547642.12435741,
              "ConditionCurrency": "67962",
              "ConditionScaleIsDeleted": true,
              "PricingScaleType": "2",
              "ConditionQuantity": 1425,
              "ConditionQuantityUnit": "962",
              "PurContrCndnQtyUnitISOCode": "962",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            },
            {
              "PurchaseContract": "es-9167963",
              "PurchaseContractItem": "67963",
              "ConditionRecord": "es-9167963",
              "ConditionSequentialNumber": "63",
              "ConditionValidityEndDate": "2008-09-08",
              "ConditionScaleLine": "7963",
              "ConditionScaleQuantity": 21278002.694,
              "ConditionScaleQuantityUnit": "963",
              "PurContrCndnScQtyUnitISOCode": "963",
              "ConditionScaleAmount": 1545248.159,
              "ConditionScaleAmountCurrency": "67963",
              "ConditionRateValue": 14165268.179,
              "ConditionRateValueUnit": "67963",
              "ConditionRateRatio": 27216944.719933,
              "ConditionRateRatioUnit": "963",
              "PurContrCndnRateRatioUntISOCd": "963",
              "ConditionRateAmount": 12153286.28173042,
              "ConditionCurrency": "67963",
              "ConditionScaleIsDeleted": false,
              "PricingScaleType": "3",
              "ConditionQuantity": 23280,
              "ConditionQuantityUnit": "963",
              "PurContrCndnQtyUnitISOCode": "963",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            }
          ]
        },
        {
          "PurchaseContract": "t-20605110",
          "PurchaseContractItem": "05110",
          "ConditionRecord": "t-20605110",
          "ConditionValidityEndDate": "2010-01-19",
          "ConditionSequentialNumber": "10",
          "ConditionValidityStartDate": "2012-02-29",
          "Plant": "5110",
          "ConditionType": "5110",
          "ConditionTextID": "D-20605110",
          "ConditionCalculationType": "0",
          "ConditionRateRatioUnit": "110",
          "PurContrCndnRateRatioUntISOCd": "110",
          "ConditionRateRatio": 26251340.17031381,
          "ConditionCurrency": "05110",
          "ConditionRateAmount": 13178576.575772,
          "ConditionRateValue": 11389792.262,
          "ConditionRateValueUnit": "05110",
          "ConditionQuantity": 83082,
          "ConditionQuantityUnit": "110",
          "PurContrCndnQtyUnitISOCode": "110",
          "ConditionToBaseQtyNmrtr": 86398,
          "ConditionToBaseQtyDnmntr": 55593,
          "BaseUnit": "110",
          "PurContrBaseUnitISOCode": "110",
          "ConditionLowerLimitAmount": 30698197.9139259,
          "ConditionLowerLimitRatio": 21267529.16451564,
          "ConditionUpperLimitAmount": 17844467.15395563,
          "ConditionUpperLimitRatio": 19061507.18534103,
          "ConditionAlternativeCurrency": "05110",
          "ConditionExclusion": "0",
          "ConditionIsDeleted": true,
          "AdditionalValueDays": "10",
          "FixedValueDate": "2015-08-01",
          "PaymentTerms": "5110",
          "CndnMaxNumberOfSalesOrders": "10",
          "MinimumConditionBasisValue": 13958453.209,
          "MaximumConditionBasisValue": 26462985.189,
          "MaximumConditionAmount": 18951324.208,
          "ConditionReleaseStatus": "0",
          "ConditionChangeReason": "110",
          "PricingScaleType": "0",
          "PricingScaleBasis": "0",
          "PricingScaleLine": "5110",
          "ConditionHasScales": true,
          "PricingScaleCheckingRule": "0",
          "to_PurchaseContract": {
            "PurchaseContract": "t-14594454"
          },
          "to_PurContrItmCndnScales": [
            {
              "PurchaseContract": "s-25840653",
              "PurchaseContractItem": "40653",
              "ConditionRecord": "s-25840653",
              "ConditionSequentialNumber": "53",
              "ConditionValidityEndDate": "2002-04-01",
              "ConditionScaleLine": "0653",
              "ConditionScaleQuantity": 7636621.17,
              "ConditionScaleQuantityUnit": "653",
              "PurContrCndnScQtyUnitISOCode": "653",
              "ConditionScaleAmount": 16121869.559,
              "ConditionScaleAmountCurrency": "40653",
              "ConditionRateValue": 2055822.305,
              "ConditionRateValueUnit": "40653",
              "ConditionRateRatio": 7589820.3301014,
              "ConditionRateRatioUnit": "653",
              "PurContrCndnRateRatioUntISOCd": "653",
              "ConditionRateAmount": 23281598.28883497,
              "ConditionCurrency": "40653",
              "ConditionScaleIsDeleted": false,
              "PricingScaleType": "3",
              "ConditionQuantity": 62424,
              "ConditionQuantityUnit": "653",
              "PurContrCndnQtyUnitISOCode": "653",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            },
            {
              "PurchaseContract": "s-25840654",
              "PurchaseContractItem": "40654",
              "ConditionRecord": "s-25840654",
              "ConditionSequentialNumber": "54",
              "ConditionValidityEndDate": "2021-02-15",
              "ConditionScaleLine": "0654",
              "ConditionScaleQuantity": 27568892.307,
              "ConditionScaleQuantityUnit": "654",
              "PurContrCndnScQtyUnitISOCode": "654",
              "ConditionScaleAmount": 3260093.804,
              "ConditionScaleAmountCurrency": "40654",
              "ConditionRateValue": 10831701.398,
              "ConditionRateValueUnit": "40654",
              "ConditionRateRatio": 7461253.843177,
              "ConditionRateRatioUnit": "654",
              "PurContrCndnRateRatioUntISOCd": "654",
              "ConditionRateAmount": 783027.21601694,
              "ConditionCurrency": "40654",
              "ConditionScaleIsDeleted": true,
              "PricingScaleType": "4",
              "ConditionQuantity": 79769,
              "ConditionQuantityUnit": "654",
              "PurContrCndnQtyUnitISOCode": "654",
              "to_PurchaseContract": {
                "PurchaseContract": "t-14594454"
              }
            }
          ]
        }
      ]
    }
  ],
  "to_PurCtrAccount": [
    {
      "AccountAssignment": "A_PurCtrAccount-19286112",
      "PurchaseContractItem": "86112",
      "PurchaseContract": "t-19286112",
      "IsDeleted": true,
      "Quantity": 30457791.143,
      "OrderQuantityUnit": "112",
      "OrderQuantityUnitISOCode": "112",
      "MultipleAcctAssgmtDistrPercent": 534.2,
      "PurgDocNetAmount": 26844154.305,
      "DocumentCurrency": "86112",
      "GLAccount": "t-19286112",
      "BusinessArea": "6112",
      "CostCenter": "r-19286112",
      "SalesOrder": "r-19286112",
      "SalesOrderItem": "286112",
      "SalesOrderScheduleLine": "6112",
      "MasterFixedAsset": "set-19286112",
      "FixedAsset": "6112",
      "OrderID": "rID-19286112",
      "GoodsRecipientName": "ame-19286112",
      "UnloadingPointName": "loadingPointName-19286112",
      "ControllingArea": "6112",
      "CostObject": "ect-19286112",
      "ProfitCenter": "r-19286112",
      "ProjectNetwork": "ork-19286112",
      "RealEstateObject": "19286112",
      "PartnerAccountNumber": "r-19286112",
      "CommitmentItem": "CommitmentItem-19286112",
      "JointVentureRecoveryCode": "12",
      "FundsCenter": "sCenter-19286112",
      "FunctionalArea": "nalArea-19286112",
      "SettlementReferenceDate": "2005-08-16",
      "TaxCode": "12",
      "TaxJurisdiction": "iction-19286112",
      "NonDeductibleInputTaxAmount": 26571123.699,
      "CostCtrActivityType": "286112",
      "BusinessProcess": "ess-19286112",
      "EarmarkedFundsDocument": "t-19286112",
      "GrantID": "GrantID-19286112",
      "BudgetPeriod": "d-19286112",
      "WBSElementExternalID": "ementExternalID-19286112"
    },
    {
      "AccountAssignment": "A_PurCtrAccount-19286113",
      "PurchaseContractItem": "86113",
      "PurchaseContract": "t-19286113",
      "IsDeleted": false,
      "Quantity": 15505842.238,
      "OrderQuantityUnit": "113",
      "OrderQuantityUnitISOCode": "113",
      "MultipleAcctAssgmtDistrPercent": 532.3,
      "PurgDocNetAmount": 12933403.532,
      "DocumentCurrency": "86113",
      "GLAccount": "t-19286113",
      "BusinessArea": "6113",
      "CostCenter": "r-19286113",
      "SalesOrder": "r-19286113",
      "SalesOrderItem": "286113",
      "SalesOrderScheduleLine": "6113",
      "MasterFixedAsset": "set-19286113",
      "FixedAsset": "6113",
      "OrderID": "rID-19286113",
      "GoodsRecipientName": "ame-19286113",
      "UnloadingPointName": "loadingPointName-19286113",
      "ControllingArea": "6113",
      "CostObject": "ect-19286113",
      "ProfitCenter": "r-19286113",
      "ProjectNetwork": "ork-19286113",
      "RealEstateObject": "19286113",
      "PartnerAccountNumber": "r-19286113",
      "CommitmentItem": "CommitmentItem-19286113",
      "JointVentureRecoveryCode": "13",
      "FundsCenter": "sCenter-19286113",
      "FunctionalArea": "nalArea-19286113",
      "SettlementReferenceDate": "2009-05-10",
      "TaxCode": "13",
      "TaxJurisdiction": "iction-19286113",
      "NonDeductibleInputTaxAmount": 30764946.469,
      "CostCtrActivityType": "286113",
      "BusinessProcess": "ess-19286113",
      "EarmarkedFundsDocument": "t-19286113",
      "GrantID": "GrantID-19286113",
      "BudgetPeriod": "d-19286113",
      "WBSElementExternalID": "ementExternalID-19286113"
    }
  ],
  "to_PurCtrAddress": [
    {
      "PurchaseContract": "ss-2579503",
      "AddressID": "ss-2579503",
      "PurchaseContractItem": "79503",
      "FormOfAddress": "9503",
      "FullName": "FullName-2579503",
      "ConsigneeName3": "ConsigneeName3-2579503",
      "ConsigneeName4": "ConsigneeName4-2579503",
      "CareOfName": "CareOfName-2579503",
      "CityName": "CityName-2579503",
      "District": "District-2579503",
      "CityCode": "9503",
      "PostalCode": "de-2579503",
      "POBoxPostalCode": "de-2579503",
      "CompanyPostalCode": "de-2579503",
      "POBox": "ox-2579503",
      "POBoxDeviatingCityName": "POBoxDeviatingCityName-2579503",
      "StreetName": "StreetName-2579503",
      "HouseNumber": "er-2579503",
      "StreetPrefixName": "StreetPrefixName-2579503",
      "AdditionalStreetPrefixName": "AdditionalStreetPrefixName-2579503",
      "AdditionalStreetSuffixName": "AdditionalStreetSuffixName-2579503",
      "Building": "Building-2579503",
      "Floor": "or-2579503",
      "RoomNumber": "er-2579503",
      "Country": "503",
      "CorrespondenceLanguage": "03",
      "Region": "503",
      "AddressTimeZone": "579503",
      "TaxJurisdiction": "diction-2579503",
      "PrfrdCommMediumType": "503",
      "PhoneNumber": "PhoneNumber-2579503",
      "FaxNumber": "FaxNumber-2579503",
      "TransportZone": "ne-2579503",
      "HouseNumberSupplementText": "xt-2579503",
      "StreetSuffixName": "StreetSuffixName-2579503"
    },
    {
      "PurchaseContract": "ss-2579504",
      "AddressID": "ss-2579504",
      "PurchaseContractItem": "79504",
      "FormOfAddress": "9504",
      "FullName": "FullName-2579504",
      "ConsigneeName3": "ConsigneeName3-2579504",
      "ConsigneeName4": "ConsigneeName4-2579504",
      "CareOfName": "CareOfName-2579504",
      "CityName": "CityName-2579504",
      "District": "District-2579504",
      "CityCode": "9504",
      "PostalCode": "de-2579504",
      "POBoxPostalCode": "de-2579504",
      "CompanyPostalCode": "de-2579504",
      "POBox": "ox-2579504",
      "POBoxDeviatingCityName": "POBoxDeviatingCityName-2579504",
      "StreetName": "StreetName-2579504",
      "HouseNumber": "er-2579504",
      "StreetPrefixName": "StreetPrefixName-2579504",
      "AdditionalStreetPrefixName": "AdditionalStreetPrefixName-2579504",
      "AdditionalStreetSuffixName": "AdditionalStreetSuffixName-2579504",
      "Building": "Building-2579504",
      "Floor": "or-2579504",
      "RoomNumber": "er-2579504",
      "Country": "504",
      "CorrespondenceLanguage": "04",
      "Region": "504",
      "AddressTimeZone": "579504",
      "TaxJurisdiction": "diction-2579504",
      "PrfrdCommMediumType": "504",
      "PhoneNumber": "PhoneNumber-2579504",
      "FaxNumber": "FaxNumber-2579504",
      "TransportZone": "ne-2579504",
      "HouseNumberSupplementText": "xt-2579504",
      "StreetSuffixName": "StreetSuffixName-2579504"
    }
  ],
  "to_PurCtrItemNotes": [
    {
      "Language": "09",
      "TextObjectType": "0809",
      "ArchitecturalObjectNumber": "A_PurchaseContractItemNotes-30740809",
      "TechnicalObjectType": "s-30740809",
      "PurchaseContractItem": "40809",
      "PurchaseContract": "s-30740809",
      "NoteDescription": "NoteDescription-30740809",
      "FixedIndicator": "9"
    },
    {
      "Language": "10",
      "TextObjectType": "0810",
      "ArchitecturalObjectNumber": "A_PurchaseContractItemNotes-30740810",
      "TechnicalObjectType": "s-30740810",
      "PurchaseContractItem": "40810",
      "PurchaseContract": "s-30740810",
      "NoteDescription": "NoteDescription-30740810",
      "FixedIndicator": "0"
    }
  ],
  "to_PurchaseContract": {
    "PurchaseContract": "t-14594454"
  }
}


### A_PurchaseContractItem
# @name A_PurchaseContractItem_DELETE
DELETE {{server}}/proxy/A_PurchaseContractItem(PurchaseContract='em-8676876',PurchaseContractItem='76876')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### A_PurchaseContractNotes
# @name A_PurchaseContractNotes_GET
GET {{server}}/proxy/A_PurchaseContractNotes
Authorization: Basic {{username}}:{{password}}


### A_PurchaseContractNotes
# @name A_PurchaseContractNotes_POST
POST {{server}}/proxy/A_PurchaseContractNotes
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Language": "19",
  "TextObjectType": "3919",
  "TechnicalObjectType": "s-11583919",
  "ArchitecturalObjectNumber": "A_PurchaseContractNotes-11583919",
  "PurchaseContract": "s-11583919",
  "NoteDescription": "NoteDescription-11583919"
}


### A_PurchaseContractNotes
# @name A_PurchaseContractNotes_PATCH
PATCH {{server}}/proxy/A_PurchaseContractNotes(Language='19',TextObjectType='3919',TechnicalObjectType='s-11583919',ArchitecturalObjectNumber='A_PurchaseContractNotes-11583919',PurchaseContract='s-11583919')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Language": "19",
  "TextObjectType": "3919",
  "TechnicalObjectType": "s-11583919",
  "ArchitecturalObjectNumber": "A_PurchaseContractNotes-11583919",
  "PurchaseContract": "s-11583919",
  "NoteDescription": "NoteDescription-11583919"
}


### A_PurchaseContractNotes
# @name A_PurchaseContractNotes_DELETE
DELETE {{server}}/proxy/A_PurchaseContractNotes(Language='19',TextObjectType='3919',TechnicalObjectType='s-11583919',ArchitecturalObjectNumber='A_PurchaseContractNotes-11583919',PurchaseContract='s-11583919')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### A_PurchaseContractItemNotes
# @name A_PurchaseContractItemNotes_GET
GET {{server}}/proxy/A_PurchaseContractItemNotes
Authorization: Basic {{username}}:{{password}}


### A_PurchaseContractItemNotes
# @name A_PurchaseContractItemNotes_POST
POST {{server}}/proxy/A_PurchaseContractItemNotes
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Language": "09",
  "TextObjectType": "0809",
  "ArchitecturalObjectNumber": "A_PurchaseContractItemNotes-30740809",
  "TechnicalObjectType": "s-30740809",
  "PurchaseContractItem": "40809",
  "PurchaseContract": "s-30740809",
  "NoteDescription": "NoteDescription-30740809",
  "FixedIndicator": "9"
}


### A_PurchaseContractItemNotes
# @name A_PurchaseContractItemNotes_PATCH
PATCH {{server}}/proxy/A_PurchaseContractItemNotes(Language='09',TextObjectType='0809',ArchitecturalObjectNumber='A_PurchaseContractItemNotes-30740809',TechnicalObjectType='s-30740809',PurchaseContractItem='40809',PurchaseContract='s-30740809')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Language": "09",
  "TextObjectType": "0809",
  "ArchitecturalObjectNumber": "A_PurchaseContractItemNotes-30740809",
  "TechnicalObjectType": "s-30740809",
  "PurchaseContractItem": "40809",
  "PurchaseContract": "s-30740809",
  "NoteDescription": "NoteDescription-30740809",
  "FixedIndicator": "9"
}


### A_PurchaseContractItemNotes
# @name A_PurchaseContractItemNotes_DELETE
DELETE {{server}}/proxy/A_PurchaseContractItemNotes(Language='09',TextObjectType='0809',ArchitecturalObjectNumber='A_PurchaseContractItemNotes-30740809',TechnicalObjectType='s-30740809',PurchaseContractItem='40809',PurchaseContract='s-30740809')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
